#!/bin/bash

${MOCKGEN:-mockgen} -package internal -destination internal/hash.go authelia.com/provider/oauth2 Hasher
${MOCKGEN:-mockgen} -package internal -destination internal/storage.go authelia.com/provider/oauth2 Storage
${MOCKGEN:-mockgen} -package internal -destination internal/transactional.go authelia.com/provider/oauth2/storage Transactional
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_storage.go authelia.com/provider/oauth2/handler/oauth2 CoreStorage
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_strategy.go authelia.com/provider/oauth2/handler/oauth2 CoreStrategy
${MOCKGEN:-mockgen} -package internal -destination internal/authorize_code_storage.go authelia.com/provider/oauth2/handler/oauth2 AuthorizeCodeStorage
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_auth_jwt_storage.go authelia.com/provider/oauth2/handler/rfc7523 RFC7523KeyStorage
${MOCKGEN:-mockgen} -package internal -destination internal/access_token_storage.go authelia.com/provider/oauth2/handler/oauth2 AccessTokenStorage
${MOCKGEN:-mockgen} -package internal -destination internal/refresh_token_strategy.go authelia.com/provider/oauth2/handler/oauth2 RefreshTokenStorage
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_client_storage.go authelia.com/provider/oauth2/handler/oauth2 ClientCredentialsGrantStorage
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_owner_storage.go authelia.com/provider/oauth2/handler/oauth2 ResourceOwnerPasswordCredentialsGrantStorage
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_revoke_storage.go authelia.com/provider/oauth2/handler/oauth2 TokenRevocationStorage
${MOCKGEN:-mockgen} -package internal -destination internal/openid_id_token_storage.go authelia.com/provider/oauth2/handler/openid OpenIDConnectRequestStorage
${MOCKGEN:-mockgen} -package internal -destination internal/access_token_strategy.go authelia.com/provider/oauth2/handler/oauth2 AccessTokenStrategy
${MOCKGEN:-mockgen} -package internal -destination internal/refresh_token_strategy.go authelia.com/provider/oauth2/handler/oauth2 RefreshTokenStrategy
${MOCKGEN:-mockgen} -package internal -destination internal/authorize_code_strategy.go authelia.com/provider/oauth2/handler/oauth2 AuthorizeCodeStrategy
${MOCKGEN:-mockgen} -package internal -destination internal/id_token_strategy.go authelia.com/provider/oauth2/handler/openid OpenIDConnectTokenStrategy
${MOCKGEN:-mockgen} -package internal -destination internal/pkce_storage_strategy.go authelia.com/provider/oauth2/handler/pkce PKCERequestStorage
${MOCKGEN:-mockgen} -package internal -destination internal/authorize_handler.go authelia.com/provider/oauth2 AuthorizeEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination internal/revoke_handler.go authelia.com/provider/oauth2 RevocationHandler
${MOCKGEN:-mockgen} -package internal -destination internal/token_handler.go authelia.com/provider/oauth2 TokenEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination internal/introspector.go authelia.com/provider/oauth2 TokenIntrospector
${MOCKGEN:-mockgen} -package internal -destination internal/client.go authelia.com/provider/oauth2 Client
${MOCKGEN:-mockgen} -package internal -destination internal/request.go authelia.com/provider/oauth2 Requester
${MOCKGEN:-mockgen} -package internal -destination internal/access_request.go authelia.com/provider/oauth2 AccessRequester
${MOCKGEN:-mockgen} -package internal -destination internal/access_response.go authelia.com/provider/oauth2 AccessResponder
${MOCKGEN:-mockgen} -package internal -destination internal/authorize_request.go authelia.com/provider/oauth2 AuthorizeRequester
${MOCKGEN:-mockgen} -package internal -destination internal/authorize_response.go authelia.com/provider/oauth2 AuthorizeResponder
${MOCKGEN:-mockgen} -package internal -destination internal/device_oauth2_handler.go authelia.com/provider/oauth2/handler/oauth2 CodeTokenEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination internal/device_handler.go authelia.com/provider/oauth2 DeviceAuthorizeEndpointHandler,RFC8628UserAuthorizeEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination internal/oauth2_device_auth_storage.go authelia.com/provider/oauth2/handler/rfc8628 RFC8628CodeStorage
${MOCKGEN:-mockgen} -package internal -destination internal/device_authorization_request.go authelia.com/provider/oauth2 DeviceAuthorizeRequester

${MOCKGEN:-mockgen} -package internal -destination testing/mock/hash.go authelia.com/provider/oauth2 Hasher
${MOCKGEN:-mockgen} -package internal -destination testing/mock/storage.go authelia.com/provider/oauth2 Storage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/transactional.go authelia.com/provider/oauth2/storage Transactional
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_storage.go authelia.com/provider/oauth2/handler/oauth2 CoreStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_strategy.go authelia.com/provider/oauth2/handler/oauth2 CoreStrategy
${MOCKGEN:-mockgen} -package internal -destination testing/mock/authorize_code_storage.go authelia.com/provider/oauth2/handler/oauth2 AuthorizeCodeStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_auth_jwt_storage.go authelia.com/provider/oauth2/handler/rfc7523 RFC7523KeyStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/access_token_storage.go authelia.com/provider/oauth2/handler/oauth2 AccessTokenStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/refresh_token_strategy.go authelia.com/provider/oauth2/handler/oauth2 RefreshTokenStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_client_storage.go authelia.com/provider/oauth2/handler/oauth2 ClientCredentialsGrantStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_owner_storage.go authelia.com/provider/oauth2/handler/oauth2 ResourceOwnerPasswordCredentialsGrantStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_revoke_storage.go authelia.com/provider/oauth2/handler/oauth2 TokenRevocationStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/openid_id_token_storage.go authelia.com/provider/oauth2/handler/openid OpenIDConnectRequestStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/access_token_strategy.go authelia.com/provider/oauth2/handler/oauth2 AccessTokenStrategy
${MOCKGEN:-mockgen} -package internal -destination testing/mock/refresh_token_strategy.go authelia.com/provider/oauth2/handler/oauth2 RefreshTokenStrategy
${MOCKGEN:-mockgen} -package internal -destination testing/mock/authorize_code_strategy.go authelia.com/provider/oauth2/handler/oauth2 AuthorizeCodeStrategy
${MOCKGEN:-mockgen} -package internal -destination testing/mock/id_token_strategy.go authelia.com/provider/oauth2/handler/openid OpenIDConnectTokenStrategy
${MOCKGEN:-mockgen} -package internal -destination testing/mock/pkce_storage_strategy.go authelia.com/provider/oauth2/handler/pkce PKCERequestStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/authorize_handler.go authelia.com/provider/oauth2 AuthorizeEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination testing/mock/revoke_handler.go authelia.com/provider/oauth2 RevocationHandler
${MOCKGEN:-mockgen} -package internal -destination testing/mock/token_handler.go authelia.com/provider/oauth2 TokenEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination testing/mock/introspector.go authelia.com/provider/oauth2 TokenIntrospector
${MOCKGEN:-mockgen} -package internal -destination testing/mock/client.go authelia.com/provider/oauth2 Client
${MOCKGEN:-mockgen} -package internal -destination testing/mock/request.go authelia.com/provider/oauth2 Requester
${MOCKGEN:-mockgen} -package internal -destination testing/mock/access_request.go authelia.com/provider/oauth2 AccessRequester
${MOCKGEN:-mockgen} -package internal -destination testing/mock/access_response.go authelia.com/provider/oauth2 AccessResponder
${MOCKGEN:-mockgen} -package internal -destination testing/mock/authorize_request.go authelia.com/provider/oauth2 AuthorizeRequester
${MOCKGEN:-mockgen} -package internal -destination testing/mock/authorize_response.go authelia.com/provider/oauth2 AuthorizeResponder
${MOCKGEN:-mockgen} -package internal -destination testing/mock/device_oauth2_handler.go authelia.com/provider/oauth2/handler/oauth2 CodeTokenEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination testing/mock/device_handler.go authelia.com/provider/oauth2 DeviceAuthorizeEndpointHandler,RFC8628UserAuthorizeEndpointHandler
${MOCKGEN:-mockgen} -package internal -destination testing/mock/oauth2_device_auth_storage.go authelia.com/provider/oauth2/handler/rfc8628 RFC8628CodeStorage
${MOCKGEN:-mockgen} -package internal -destination testing/mock/device_authorization_request.go authelia.com/provider/oauth2 DeviceAuthorizeRequester
${MOCKGEN:-mockgen} -package internal -destination testing/mock/client_secret.go authelia.com/provider/oauth2 ClientSecret