// SPDX-FileCopyrightText: 2026 Authelia
//
// SPDX-License-Identifier: Apache-2.0

package oauth2

import (
	"encoding/json"
	"io"
	"net/http"

	"authelia.com/provider/oauth2/internal/consts"
)

type DeviceAuthorizeResponse struct {
	Header                  http.Header    `json:"-"`
	DeviceCode              string         `json:"device_code"`
	UserCode                string         `json:"user_code"`
	VerificationURI         string         `json:"verification_uri"`
	VerificationURIComplete string         `json:"verification_uri_complete,omitempty"`
	ExpiresIn               int64          `json:"expires_in"`
	Interval                int            `json:"interval,omitempty"`
	Extra                   map[string]any `json:"-"`
}

// NewDeviceAuthorizeResponse returns an empty RFC 8628 device authorization response with its extras map initialized.
func NewDeviceAuthorizeResponse() *DeviceAuthorizeResponse {
	return &DeviceAuthorizeResponse{
		Extra: map[string]any{},
	}
}

// GetDeviceCode returns the device verification code generated by the authorization server per RFC 8628 section 3.2.
func (d *DeviceAuthorizeResponse) GetDeviceCode() string {
	return d.DeviceCode
}

// SetDeviceCode returns the response's user code
func (d *DeviceAuthorizeResponse) SetDeviceCode(code string) {
	d.DeviceCode = code
}

// GetUserCode returns the user code that the resource owner enters at the verification URI to authorize the device.
func (d *DeviceAuthorizeResponse) GetUserCode() string {
	return d.UserCode
}

// SetUserCode records the user code that the resource owner enters at the verification URI to authorize the device.
func (d *DeviceAuthorizeResponse) SetUserCode(code string) {
	d.UserCode = code
}

// GetVerificationURI returns the response's verification uri
func (d *DeviceAuthorizeResponse) GetVerificationURI() string {
	return d.VerificationURI
}

// SetVerificationURI records the end-user verification URI returned to the device.
func (d *DeviceAuthorizeResponse) SetVerificationURI(uri string) {
	d.VerificationURI = uri
}

// GetVerificationURIComplete returns the response's complete verification uri if set
func (d *DeviceAuthorizeResponse) GetVerificationURIComplete() string {
	return d.VerificationURIComplete
}

// SetVerificationURIComplete records the optional verification_uri_complete value that combines the verification URI
// and user code into a single URI.
func (d *DeviceAuthorizeResponse) SetVerificationURIComplete(uri string) {
	d.VerificationURIComplete = uri
}

// GetExpiresIn returns the response's device code and user code lifetime in seconds if set
func (d *DeviceAuthorizeResponse) GetExpiresIn() int64 {
	return d.ExpiresIn
}

// SetExpiresIn records the lifetime of the device code and user code in seconds.
func (d *DeviceAuthorizeResponse) SetExpiresIn(seconds int64) {
	d.ExpiresIn = seconds
}

// GetInterval returns the response's polling interval if set
func (d *DeviceAuthorizeResponse) GetInterval() int {
	return d.Interval
}

// SetInterval records the minimum polling interval, in seconds, that the device must observe when polling the token
// endpoint.
func (d *DeviceAuthorizeResponse) SetInterval(seconds int) {
	d.Interval = seconds
}

// GetHeader returns the response HTTP headers that will be written to the client.
func (d *DeviceAuthorizeResponse) GetHeader() http.Header {
	return d.Header
}

// AddHeader appends the value to the named response header.
func (d *DeviceAuthorizeResponse) AddHeader(key, value string) {
	d.Header.Add(key, value)
}

// FromJSON decodes a JSON-encoded device authorization response from r into the receiver.
func (d *DeviceAuthorizeResponse) FromJSON(r io.Reader) error {
	return json.NewDecoder(r).Decode(&d)
}

// ToMap converts the response to a map.
func (d *DeviceAuthorizeResponse) ToMap() map[string]any {
	d.Extra[consts.DeviceCodeResponseDeviceCode] = d.DeviceCode
	d.Extra[consts.DeviceCodeResponseUserCode] = d.UserCode
	d.Extra[consts.DeviceCodeResponseVerificationURI] = d.VerificationURI
	d.Extra[consts.DeviceCodeResponseVerificationURIComplete] = d.VerificationURIComplete
	d.Extra[consts.DeviceCodeResponseExpiresIn] = d.ExpiresIn
	d.Extra[consts.DeviceCodeResponseInterval] = d.Interval

	return d.Extra
}

// SetExtra sets an extension parameter on the response, allowing handlers to inject additional response fields.
func (d *DeviceAuthorizeResponse) SetExtra(key string, value any) {
	d.Extra[key] = value
}

// GetExtra returns the value previously stored under key by SetExtra, or nil if none has been set.
func (d *DeviceAuthorizeResponse) GetExtra(key string) any {
	return d.Extra[key]
}

var (
	_ DeviceAuthorizeResponder = (*DeviceAuthorizeResponse)(nil)
)
