// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2 (interfaces: OpenIDCIBAEndpointHandler)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/ciba_handler.go authelia.com/provider/oauth2 OpenIDCIBAEndpointHandler
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockOpenIDCIBAEndpointHandler is a mock of OpenIDCIBAEndpointHandler interface.
type MockOpenIDCIBAEndpointHandler struct {
	ctrl     *gomock.Controller
	recorder *MockOpenIDCIBAEndpointHandlerMockRecorder
	isgomock struct{}
}

// MockOpenIDCIBAEndpointHandlerMockRecorder is the mock recorder for MockOpenIDCIBAEndpointHandler.
type MockOpenIDCIBAEndpointHandlerMockRecorder struct {
	mock *MockOpenIDCIBAEndpointHandler
}

// NewMockOpenIDCIBAEndpointHandler creates a new mock instance.
func NewMockOpenIDCIBAEndpointHandler(ctrl *gomock.Controller) *MockOpenIDCIBAEndpointHandler {
	mock := &MockOpenIDCIBAEndpointHandler{ctrl: ctrl}
	mock.recorder = &MockOpenIDCIBAEndpointHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOpenIDCIBAEndpointHandler) EXPECT() *MockOpenIDCIBAEndpointHandlerMockRecorder {
	return m.recorder
}

// HandleOpenIDCIBAEndpointRequest mocks base method.
func (m *MockOpenIDCIBAEndpointHandler) HandleOpenIDCIBAEndpointRequest(ctx context.Context, request oauth2.CIBARequester, response oauth2.CIBAResponder) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleOpenIDCIBAEndpointRequest", ctx, request, response)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleOpenIDCIBAEndpointRequest indicates an expected call of HandleOpenIDCIBAEndpointRequest.
func (mr *MockOpenIDCIBAEndpointHandlerMockRecorder) HandleOpenIDCIBAEndpointRequest(ctx, request, response any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleOpenIDCIBAEndpointRequest", reflect.TypeOf((*MockOpenIDCIBAEndpointHandler)(nil).HandleOpenIDCIBAEndpointRequest), ctx, request, response)
}
