// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2 (interfaces: CIBARequester)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/ciba_request.go authelia.com/provider/oauth2 CIBARequester
//

// Package mock is a generated GoMock package.
package mock

import (
	url "net/url"
	reflect "reflect"
	time "time"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockCIBARequester is a mock of CIBARequester interface.
type MockCIBARequester struct {
	ctrl     *gomock.Controller
	recorder *MockCIBARequesterMockRecorder
	isgomock struct{}
}

// MockCIBARequesterMockRecorder is the mock recorder for MockCIBARequester.
type MockCIBARequesterMockRecorder struct {
	mock *MockCIBARequester
}

// NewMockCIBARequester creates a new mock instance.
func NewMockCIBARequester(ctrl *gomock.Controller) *MockCIBARequester {
	mock := &MockCIBARequester{ctrl: ctrl}
	mock.recorder = &MockCIBARequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCIBARequester) EXPECT() *MockCIBARequesterMockRecorder {
	return m.recorder
}

// AppendRequestedScope mocks base method.
func (m *MockCIBARequester) AppendRequestedScope(scope string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendRequestedScope", scope)
}

// AppendRequestedScope indicates an expected call of AppendRequestedScope.
func (mr *MockCIBARequesterMockRecorder) AppendRequestedScope(scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRequestedScope", reflect.TypeOf((*MockCIBARequester)(nil).AppendRequestedScope), scope)
}

// GetAuthRequestIDSignature mocks base method.
func (m *MockCIBARequester) GetAuthRequestIDSignature() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthRequestIDSignature")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetAuthRequestIDSignature indicates an expected call of GetAuthRequestIDSignature.
func (mr *MockCIBARequesterMockRecorder) GetAuthRequestIDSignature() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthRequestIDSignature", reflect.TypeOf((*MockCIBARequester)(nil).GetAuthRequestIDSignature))
}

// GetClient mocks base method.
func (m *MockCIBARequester) GetClient() oauth2.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(oauth2.Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockCIBARequesterMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockCIBARequester)(nil).GetClient))
}

// GetGrantedAudience mocks base method.
func (m *MockCIBARequester) GetGrantedAudience() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantedAudience")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetGrantedAudience indicates an expected call of GetGrantedAudience.
func (mr *MockCIBARequesterMockRecorder) GetGrantedAudience() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantedAudience", reflect.TypeOf((*MockCIBARequester)(nil).GetGrantedAudience))
}

// GetGrantedResource mocks base method.
func (m *MockCIBARequester) GetGrantedResource() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantedResource")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetGrantedResource indicates an expected call of GetGrantedResource.
func (mr *MockCIBARequesterMockRecorder) GetGrantedResource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantedResource", reflect.TypeOf((*MockCIBARequester)(nil).GetGrantedResource))
}

// GetGrantedScopes mocks base method.
func (m *MockCIBARequester) GetGrantedScopes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantedScopes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetGrantedScopes indicates an expected call of GetGrantedScopes.
func (mr *MockCIBARequesterMockRecorder) GetGrantedScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantedScopes", reflect.TypeOf((*MockCIBARequester)(nil).GetGrantedScopes))
}

// GetID mocks base method.
func (m *MockCIBARequester) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockCIBARequesterMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockCIBARequester)(nil).GetID))
}

// GetLastChecked mocks base method.
func (m *MockCIBARequester) GetLastChecked() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastChecked")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetLastChecked indicates an expected call of GetLastChecked.
func (mr *MockCIBARequesterMockRecorder) GetLastChecked() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastChecked", reflect.TypeOf((*MockCIBARequester)(nil).GetLastChecked))
}

// GetRequestForm mocks base method.
func (m *MockCIBARequester) GetRequestForm() url.Values {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestForm")
	ret0, _ := ret[0].(url.Values)
	return ret0
}

// GetRequestForm indicates an expected call of GetRequestForm.
func (mr *MockCIBARequesterMockRecorder) GetRequestForm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestForm", reflect.TypeOf((*MockCIBARequester)(nil).GetRequestForm))
}

// GetRequestedAt mocks base method.
func (m *MockCIBARequester) GetRequestedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetRequestedAt indicates an expected call of GetRequestedAt.
func (mr *MockCIBARequesterMockRecorder) GetRequestedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedAt", reflect.TypeOf((*MockCIBARequester)(nil).GetRequestedAt))
}

// GetRequestedAudience mocks base method.
func (m *MockCIBARequester) GetRequestedAudience() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedAudience")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetRequestedAudience indicates an expected call of GetRequestedAudience.
func (mr *MockCIBARequesterMockRecorder) GetRequestedAudience() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedAudience", reflect.TypeOf((*MockCIBARequester)(nil).GetRequestedAudience))
}

// GetRequestedResource mocks base method.
func (m *MockCIBARequester) GetRequestedResource() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedResource")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetRequestedResource indicates an expected call of GetRequestedResource.
func (mr *MockCIBARequesterMockRecorder) GetRequestedResource() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedResource", reflect.TypeOf((*MockCIBARequester)(nil).GetRequestedResource))
}

// GetRequestedScopes mocks base method.
func (m *MockCIBARequester) GetRequestedScopes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedScopes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetRequestedScopes indicates an expected call of GetRequestedScopes.
func (mr *MockCIBARequesterMockRecorder) GetRequestedScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedScopes", reflect.TypeOf((*MockCIBARequester)(nil).GetRequestedScopes))
}

// GetSession mocks base method.
func (m *MockCIBARequester) GetSession() oauth2.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession")
	ret0, _ := ret[0].(oauth2.Session)
	return ret0
}

// GetSession indicates an expected call of GetSession.
func (mr *MockCIBARequesterMockRecorder) GetSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockCIBARequester)(nil).GetSession))
}

// GetStatus mocks base method.
func (m *MockCIBARequester) GetStatus() oauth2.CIBAStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(oauth2.CIBAStatus)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockCIBARequesterMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockCIBARequester)(nil).GetStatus))
}

// GrantAudience mocks base method.
func (m *MockCIBARequester) GrantAudience(audience string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrantAudience", audience)
}

// GrantAudience indicates an expected call of GrantAudience.
func (mr *MockCIBARequesterMockRecorder) GrantAudience(audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAudience", reflect.TypeOf((*MockCIBARequester)(nil).GrantAudience), audience)
}

// GrantResource mocks base method.
func (m *MockCIBARequester) GrantResource(resource string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrantResource", resource)
}

// GrantResource indicates an expected call of GrantResource.
func (mr *MockCIBARequesterMockRecorder) GrantResource(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantResource", reflect.TypeOf((*MockCIBARequester)(nil).GrantResource), resource)
}

// GrantScope mocks base method.
func (m *MockCIBARequester) GrantScope(scope string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrantScope", scope)
}

// GrantScope indicates an expected call of GrantScope.
func (mr *MockCIBARequesterMockRecorder) GrantScope(scope any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantScope", reflect.TypeOf((*MockCIBARequester)(nil).GrantScope), scope)
}

// Merge mocks base method.
func (m *MockCIBARequester) Merge(requester oauth2.Requester) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Merge", requester)
}

// Merge indicates an expected call of Merge.
func (mr *MockCIBARequesterMockRecorder) Merge(requester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockCIBARequester)(nil).Merge), requester)
}

// Sanitize mocks base method.
func (m *MockCIBARequester) Sanitize(allowedParameters []string) oauth2.Requester {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sanitize", allowedParameters)
	ret0, _ := ret[0].(oauth2.Requester)
	return ret0
}

// Sanitize indicates an expected call of Sanitize.
func (mr *MockCIBARequesterMockRecorder) Sanitize(allowedParameters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sanitize", reflect.TypeOf((*MockCIBARequester)(nil).Sanitize), allowedParameters)
}

// SetAuthRequestIDSignature mocks base method.
func (m *MockCIBARequester) SetAuthRequestIDSignature(signature string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetAuthRequestIDSignature", signature)
}

// SetAuthRequestIDSignature indicates an expected call of SetAuthRequestIDSignature.
func (mr *MockCIBARequesterMockRecorder) SetAuthRequestIDSignature(signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAuthRequestIDSignature", reflect.TypeOf((*MockCIBARequester)(nil).SetAuthRequestIDSignature), signature)
}

// SetID mocks base method.
func (m *MockCIBARequester) SetID(id string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetID", id)
}

// SetID indicates an expected call of SetID.
func (mr *MockCIBARequesterMockRecorder) SetID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockCIBARequester)(nil).SetID), id)
}

// SetLastChecked mocks base method.
func (m *MockCIBARequester) SetLastChecked(lastChecked time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLastChecked", lastChecked)
}

// SetLastChecked indicates an expected call of SetLastChecked.
func (mr *MockCIBARequesterMockRecorder) SetLastChecked(lastChecked any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastChecked", reflect.TypeOf((*MockCIBARequester)(nil).SetLastChecked), lastChecked)
}

// SetRequestedAt mocks base method.
func (m *MockCIBARequester) SetRequestedAt(rat time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedAt", rat)
}

// SetRequestedAt indicates an expected call of SetRequestedAt.
func (mr *MockCIBARequesterMockRecorder) SetRequestedAt(rat any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedAt", reflect.TypeOf((*MockCIBARequester)(nil).SetRequestedAt), rat)
}

// SetRequestedAudience mocks base method.
func (m *MockCIBARequester) SetRequestedAudience(audience oauth2.Arguments) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedAudience", audience)
}

// SetRequestedAudience indicates an expected call of SetRequestedAudience.
func (mr *MockCIBARequesterMockRecorder) SetRequestedAudience(audience any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedAudience", reflect.TypeOf((*MockCIBARequester)(nil).SetRequestedAudience), audience)
}

// SetRequestedResource mocks base method.
func (m *MockCIBARequester) SetRequestedResource(resource oauth2.Arguments) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedResource", resource)
}

// SetRequestedResource indicates an expected call of SetRequestedResource.
func (mr *MockCIBARequesterMockRecorder) SetRequestedResource(resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedResource", reflect.TypeOf((*MockCIBARequester)(nil).SetRequestedResource), resource)
}

// SetRequestedScopes mocks base method.
func (m *MockCIBARequester) SetRequestedScopes(scopes oauth2.Arguments) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedScopes", scopes)
}

// SetRequestedScopes indicates an expected call of SetRequestedScopes.
func (mr *MockCIBARequesterMockRecorder) SetRequestedScopes(scopes any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedScopes", reflect.TypeOf((*MockCIBARequester)(nil).SetRequestedScopes), scopes)
}

// SetSession mocks base method.
func (m *MockCIBARequester) SetSession(session oauth2.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSession", session)
}

// SetSession indicates an expected call of SetSession.
func (mr *MockCIBARequesterMockRecorder) SetSession(session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockCIBARequester)(nil).SetSession), session)
}

// SetStatus mocks base method.
func (m *MockCIBARequester) SetStatus(status oauth2.CIBAStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", status)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockCIBARequesterMockRecorder) SetStatus(status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockCIBARequester)(nil).SetStatus), status)
}
