// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2 (interfaces: DeviceAuthorizeRequester)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/device_authorization_request.go authelia.com/provider/oauth2 DeviceAuthorizeRequester
//

// Package mock is a generated GoMock package.
package mock

import (
	url "net/url"
	reflect "reflect"
	time "time"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockDeviceAuthorizeRequester is a mock of DeviceAuthorizeRequester interface.
type MockDeviceAuthorizeRequester struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAuthorizeRequesterMockRecorder
}

// MockDeviceAuthorizeRequesterMockRecorder is the mock recorder for MockDeviceAuthorizeRequester.
type MockDeviceAuthorizeRequesterMockRecorder struct {
	mock *MockDeviceAuthorizeRequester
}

// NewMockDeviceAuthorizeRequester creates a new mock instance.
func NewMockDeviceAuthorizeRequester(ctrl *gomock.Controller) *MockDeviceAuthorizeRequester {
	mock := &MockDeviceAuthorizeRequester{ctrl: ctrl}
	mock.recorder = &MockDeviceAuthorizeRequesterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAuthorizeRequester) EXPECT() *MockDeviceAuthorizeRequesterMockRecorder {
	return m.recorder
}

// AppendRequestedScope mocks base method.
func (m *MockDeviceAuthorizeRequester) AppendRequestedScope(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendRequestedScope", arg0)
}

// AppendRequestedScope indicates an expected call of AppendRequestedScope.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) AppendRequestedScope(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendRequestedScope", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).AppendRequestedScope), arg0)
}

// GetClient mocks base method.
func (m *MockDeviceAuthorizeRequester) GetClient() oauth2.Client {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient")
	ret0, _ := ret[0].(oauth2.Client)
	return ret0
}

// GetClient indicates an expected call of GetClient.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetClient() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetClient))
}

// GetDeviceCodeSignature mocks base method.
func (m *MockDeviceAuthorizeRequester) GetDeviceCodeSignature() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCodeSignature")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDeviceCodeSignature indicates an expected call of GetDeviceCodeSignature.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetDeviceCodeSignature() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCodeSignature", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetDeviceCodeSignature))
}

// GetGrantedAudience mocks base method.
func (m *MockDeviceAuthorizeRequester) GetGrantedAudience() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantedAudience")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetGrantedAudience indicates an expected call of GetGrantedAudience.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetGrantedAudience() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantedAudience", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetGrantedAudience))
}

// GetGrantedScopes mocks base method.
func (m *MockDeviceAuthorizeRequester) GetGrantedScopes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGrantedScopes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetGrantedScopes indicates an expected call of GetGrantedScopes.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetGrantedScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGrantedScopes", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetGrantedScopes))
}

// GetID mocks base method.
func (m *MockDeviceAuthorizeRequester) GetID() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetID indicates an expected call of GetID.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetID() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetID", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetID))
}

// GetLastChecked mocks base method.
func (m *MockDeviceAuthorizeRequester) GetLastChecked() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastChecked")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetLastChecked indicates an expected call of GetLastChecked.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetLastChecked() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastChecked", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetLastChecked))
}

// GetRequestForm mocks base method.
func (m *MockDeviceAuthorizeRequester) GetRequestForm() url.Values {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestForm")
	ret0, _ := ret[0].(url.Values)
	return ret0
}

// GetRequestForm indicates an expected call of GetRequestForm.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetRequestForm() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestForm", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetRequestForm))
}

// GetRequestedAt mocks base method.
func (m *MockDeviceAuthorizeRequester) GetRequestedAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// GetRequestedAt indicates an expected call of GetRequestedAt.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetRequestedAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedAt", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetRequestedAt))
}

// GetRequestedAudience mocks base method.
func (m *MockDeviceAuthorizeRequester) GetRequestedAudience() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedAudience")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetRequestedAudience indicates an expected call of GetRequestedAudience.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetRequestedAudience() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedAudience", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetRequestedAudience))
}

// GetRequestedScopes mocks base method.
func (m *MockDeviceAuthorizeRequester) GetRequestedScopes() oauth2.Arguments {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRequestedScopes")
	ret0, _ := ret[0].(oauth2.Arguments)
	return ret0
}

// GetRequestedScopes indicates an expected call of GetRequestedScopes.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetRequestedScopes() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRequestedScopes", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetRequestedScopes))
}

// GetSession mocks base method.
func (m *MockDeviceAuthorizeRequester) GetSession() oauth2.Session {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSession")
	ret0, _ := ret[0].(oauth2.Session)
	return ret0
}

// GetSession indicates an expected call of GetSession.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetSession() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSession", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetSession))
}

// GetStatus mocks base method.
func (m *MockDeviceAuthorizeRequester) GetStatus() oauth2.DeviceAuthorizeStatus {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStatus")
	ret0, _ := ret[0].(oauth2.DeviceAuthorizeStatus)
	return ret0
}

// GetStatus indicates an expected call of GetStatus.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetStatus() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStatus", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetStatus))
}

// GetUserCodeSignature mocks base method.
func (m *MockDeviceAuthorizeRequester) GetUserCodeSignature() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCodeSignature")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserCodeSignature indicates an expected call of GetUserCodeSignature.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GetUserCodeSignature() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCodeSignature", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GetUserCodeSignature))
}

// GrantAudience mocks base method.
func (m *MockDeviceAuthorizeRequester) GrantAudience(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrantAudience", arg0)
}

// GrantAudience indicates an expected call of GrantAudience.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GrantAudience(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantAudience", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GrantAudience), arg0)
}

// GrantScope mocks base method.
func (m *MockDeviceAuthorizeRequester) GrantScope(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GrantScope", arg0)
}

// GrantScope indicates an expected call of GrantScope.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) GrantScope(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GrantScope", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).GrantScope), arg0)
}

// Merge mocks base method.
func (m *MockDeviceAuthorizeRequester) Merge(arg0 oauth2.Requester) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Merge", arg0)
}

// Merge indicates an expected call of Merge.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) Merge(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Merge", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).Merge), arg0)
}

// Sanitize mocks base method.
func (m *MockDeviceAuthorizeRequester) Sanitize(arg0 []string) oauth2.Requester {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Sanitize", arg0)
	ret0, _ := ret[0].(oauth2.Requester)
	return ret0
}

// Sanitize indicates an expected call of Sanitize.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) Sanitize(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Sanitize", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).Sanitize), arg0)
}

// SetDeviceCodeSignature mocks base method.
func (m *MockDeviceAuthorizeRequester) SetDeviceCodeSignature(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDeviceCodeSignature", arg0)
}

// SetDeviceCodeSignature indicates an expected call of SetDeviceCodeSignature.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetDeviceCodeSignature(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeviceCodeSignature", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetDeviceCodeSignature), arg0)
}

// SetID mocks base method.
func (m *MockDeviceAuthorizeRequester) SetID(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetID", arg0)
}

// SetID indicates an expected call of SetID.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetID(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetID", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetID), arg0)
}

// SetLastChecked mocks base method.
func (m *MockDeviceAuthorizeRequester) SetLastChecked(arg0 time.Time) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetLastChecked", arg0)
}

// SetLastChecked indicates an expected call of SetLastChecked.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetLastChecked(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastChecked", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetLastChecked), arg0)
}

// SetRequestedAudience mocks base method.
func (m *MockDeviceAuthorizeRequester) SetRequestedAudience(arg0 oauth2.Arguments) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedAudience", arg0)
}

// SetRequestedAudience indicates an expected call of SetRequestedAudience.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetRequestedAudience(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedAudience", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetRequestedAudience), arg0)
}

// SetRequestedScopes mocks base method.
func (m *MockDeviceAuthorizeRequester) SetRequestedScopes(arg0 oauth2.Arguments) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetRequestedScopes", arg0)
}

// SetRequestedScopes indicates an expected call of SetRequestedScopes.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetRequestedScopes(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetRequestedScopes", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetRequestedScopes), arg0)
}

// SetSession mocks base method.
func (m *MockDeviceAuthorizeRequester) SetSession(arg0 oauth2.Session) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetSession", arg0)
}

// SetSession indicates an expected call of SetSession.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetSession(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSession", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetSession), arg0)
}

// SetStatus mocks base method.
func (m *MockDeviceAuthorizeRequester) SetStatus(arg0 oauth2.DeviceAuthorizeStatus) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetStatus", arg0)
}

// SetStatus indicates an expected call of SetStatus.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetStatus(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetStatus", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetStatus), arg0)
}

// SetUserCodeSignature mocks base method.
func (m *MockDeviceAuthorizeRequester) SetUserCodeSignature(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserCodeSignature", arg0)
}

// SetUserCodeSignature indicates an expected call of SetUserCodeSignature.
func (mr *MockDeviceAuthorizeRequesterMockRecorder) SetUserCodeSignature(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserCodeSignature", reflect.TypeOf((*MockDeviceAuthorizeRequester)(nil).SetUserCodeSignature), arg0)
}
