// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2/handler/rfc8628 (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/oauth2_device_auth_storage.go -mock_names Storage=MockRFC8628Storage authelia.com/provider/oauth2/handler/rfc8628 Storage
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockRFC8628Storage is a mock of Storage interface.
type MockRFC8628Storage struct {
	ctrl     *gomock.Controller
	recorder *MockRFC8628StorageMockRecorder
	isgomock struct{}
}

// MockRFC8628StorageMockRecorder is the mock recorder for MockRFC8628Storage.
type MockRFC8628StorageMockRecorder struct {
	mock *MockRFC8628Storage
}

// NewMockRFC8628Storage creates a new mock instance.
func NewMockRFC8628Storage(ctrl *gomock.Controller) *MockRFC8628Storage {
	mock := &MockRFC8628Storage{ctrl: ctrl}
	mock.recorder = &MockRFC8628StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRFC8628Storage) EXPECT() *MockRFC8628StorageMockRecorder {
	return m.recorder
}

// CreateDeviceCodeSession mocks base method.
func (m *MockRFC8628Storage) CreateDeviceCodeSession(ctx context.Context, signature string, request oauth2.DeviceAuthorizeRequester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateDeviceCodeSession", ctx, signature, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateDeviceCodeSession indicates an expected call of CreateDeviceCodeSession.
func (mr *MockRFC8628StorageMockRecorder) CreateDeviceCodeSession(ctx, signature, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateDeviceCodeSession", reflect.TypeOf((*MockRFC8628Storage)(nil).CreateDeviceCodeSession), ctx, signature, request)
}

// GetDeviceCodeSession mocks base method.
func (m *MockRFC8628Storage) GetDeviceCodeSession(ctx context.Context, signature string, session oauth2.Session) (oauth2.DeviceAuthorizeRequester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCodeSession", ctx, signature, session)
	ret0, _ := ret[0].(oauth2.DeviceAuthorizeRequester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCodeSession indicates an expected call of GetDeviceCodeSession.
func (mr *MockRFC8628StorageMockRecorder) GetDeviceCodeSession(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCodeSession", reflect.TypeOf((*MockRFC8628Storage)(nil).GetDeviceCodeSession), ctx, signature, session)
}

// GetDeviceCodeSessionByUserCode mocks base method.
func (m *MockRFC8628Storage) GetDeviceCodeSessionByUserCode(ctx context.Context, signature string, session oauth2.Session) (oauth2.DeviceAuthorizeRequester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCodeSessionByUserCode", ctx, signature, session)
	ret0, _ := ret[0].(oauth2.DeviceAuthorizeRequester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDeviceCodeSessionByUserCode indicates an expected call of GetDeviceCodeSessionByUserCode.
func (mr *MockRFC8628StorageMockRecorder) GetDeviceCodeSessionByUserCode(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCodeSessionByUserCode", reflect.TypeOf((*MockRFC8628Storage)(nil).GetDeviceCodeSessionByUserCode), ctx, signature, session)
}

// InvalidateDeviceCodeSession mocks base method.
func (m *MockRFC8628Storage) InvalidateDeviceCodeSession(ctx context.Context, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateDeviceCodeSession", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateDeviceCodeSession indicates an expected call of InvalidateDeviceCodeSession.
func (mr *MockRFC8628StorageMockRecorder) InvalidateDeviceCodeSession(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateDeviceCodeSession", reflect.TypeOf((*MockRFC8628Storage)(nil).InvalidateDeviceCodeSession), ctx, signature)
}

// UpdateDeviceCodeSession mocks base method.
func (m *MockRFC8628Storage) UpdateDeviceCodeSession(ctx context.Context, signature string, request oauth2.DeviceAuthorizeRequester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateDeviceCodeSession", ctx, signature, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateDeviceCodeSession indicates an expected call of UpdateDeviceCodeSession.
func (mr *MockRFC8628StorageMockRecorder) UpdateDeviceCodeSession(ctx, signature, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateDeviceCodeSession", reflect.TypeOf((*MockRFC8628Storage)(nil).UpdateDeviceCodeSession), ctx, signature, request)
}
