// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2/handler/rfc7523 (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/oauth2_auth_jwt_storage.go -mock_names Storage=MockRFC7523Storage authelia.com/provider/oauth2/handler/rfc7523 Storage
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	jose "authelia.com/provider/oauth2/token/jose"
	gomock "go.uber.org/mock/gomock"
)

// MockRFC7523Storage is a mock of Storage interface.
type MockRFC7523Storage struct {
	ctrl     *gomock.Controller
	recorder *MockRFC7523StorageMockRecorder
	isgomock struct{}
}

// MockRFC7523StorageMockRecorder is the mock recorder for MockRFC7523Storage.
type MockRFC7523StorageMockRecorder struct {
	mock *MockRFC7523Storage
}

// NewMockRFC7523Storage creates a new mock instance.
func NewMockRFC7523Storage(ctrl *gomock.Controller) *MockRFC7523Storage {
	mock := &MockRFC7523Storage{ctrl: ctrl}
	mock.recorder = &MockRFC7523StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRFC7523Storage) EXPECT() *MockRFC7523StorageMockRecorder {
	return m.recorder
}

// GetRFC7523PublicKey mocks base method.
func (m *MockRFC7523Storage) GetRFC7523PublicKey(ctx context.Context, issuer, subject, keyId string) (*jose.JSONWebKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRFC7523PublicKey", ctx, issuer, subject, keyId)
	ret0, _ := ret[0].(*jose.JSONWebKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRFC7523PublicKey indicates an expected call of GetRFC7523PublicKey.
func (mr *MockRFC7523StorageMockRecorder) GetRFC7523PublicKey(ctx, issuer, subject, keyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRFC7523PublicKey", reflect.TypeOf((*MockRFC7523Storage)(nil).GetRFC7523PublicKey), ctx, issuer, subject, keyId)
}

// GetRFC7523PublicKeyScopes mocks base method.
func (m *MockRFC7523Storage) GetRFC7523PublicKeyScopes(ctx context.Context, issuer, subject, keyId string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRFC7523PublicKeyScopes", ctx, issuer, subject, keyId)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRFC7523PublicKeyScopes indicates an expected call of GetRFC7523PublicKeyScopes.
func (mr *MockRFC7523StorageMockRecorder) GetRFC7523PublicKeyScopes(ctx, issuer, subject, keyId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRFC7523PublicKeyScopes", reflect.TypeOf((*MockRFC7523Storage)(nil).GetRFC7523PublicKeyScopes), ctx, issuer, subject, keyId)
}

// GetRFC7523PublicKeys mocks base method.
func (m *MockRFC7523Storage) GetRFC7523PublicKeys(ctx context.Context, issuer, subject string) (*jose.JSONWebKeySet, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRFC7523PublicKeys", ctx, issuer, subject)
	ret0, _ := ret[0].(*jose.JSONWebKeySet)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRFC7523PublicKeys indicates an expected call of GetRFC7523PublicKeys.
func (mr *MockRFC7523StorageMockRecorder) GetRFC7523PublicKeys(ctx, issuer, subject any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRFC7523PublicKeys", reflect.TypeOf((*MockRFC7523Storage)(nil).GetRFC7523PublicKeys), ctx, issuer, subject)
}

// IsRFC7523JWTUsed mocks base method.
func (m *MockRFC7523Storage) IsRFC7523JWTUsed(ctx context.Context, issuer, jti string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRFC7523JWTUsed", ctx, issuer, jti)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsRFC7523JWTUsed indicates an expected call of IsRFC7523JWTUsed.
func (mr *MockRFC7523StorageMockRecorder) IsRFC7523JWTUsed(ctx, issuer, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRFC7523JWTUsed", reflect.TypeOf((*MockRFC7523Storage)(nil).IsRFC7523JWTUsed), ctx, issuer, jti)
}

// MarkRFC7523JWTUsedForTime mocks base method.
func (m *MockRFC7523Storage) MarkRFC7523JWTUsedForTime(ctx context.Context, issuer, jti string, exp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkRFC7523JWTUsedForTime", ctx, issuer, jti, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkRFC7523JWTUsedForTime indicates an expected call of MarkRFC7523JWTUsedForTime.
func (mr *MockRFC7523StorageMockRecorder) MarkRFC7523JWTUsedForTime(ctx, issuer, jti, exp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkRFC7523JWTUsedForTime", reflect.TypeOf((*MockRFC7523Storage)(nil).MarkRFC7523JWTUsedForTime), ctx, issuer, jti, exp)
}
