// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2 (interfaces: PARStorage)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/par_storage.go authelia.com/provider/oauth2 PARStorage
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockPARStorage is a mock of PARStorage interface.
type MockPARStorage struct {
	ctrl     *gomock.Controller
	recorder *MockPARStorageMockRecorder
	isgomock struct{}
}

// MockPARStorageMockRecorder is the mock recorder for MockPARStorage.
type MockPARStorageMockRecorder struct {
	mock *MockPARStorage
}

// NewMockPARStorage creates a new mock instance.
func NewMockPARStorage(ctrl *gomock.Controller) *MockPARStorage {
	mock := &MockPARStorage{ctrl: ctrl}
	mock.recorder = &MockPARStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPARStorage) EXPECT() *MockPARStorageMockRecorder {
	return m.recorder
}

// CreatePARSession mocks base method.
func (m *MockPARStorage) CreatePARSession(ctx context.Context, requestURI string, request oauth2.AuthorizeRequester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePARSession", ctx, requestURI, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePARSession indicates an expected call of CreatePARSession.
func (mr *MockPARStorageMockRecorder) CreatePARSession(ctx, requestURI, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePARSession", reflect.TypeOf((*MockPARStorage)(nil).CreatePARSession), ctx, requestURI, request)
}

// DeletePARSession mocks base method.
func (m *MockPARStorage) DeletePARSession(ctx context.Context, requestURI string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePARSession", ctx, requestURI)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePARSession indicates an expected call of DeletePARSession.
func (mr *MockPARStorageMockRecorder) DeletePARSession(ctx, requestURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePARSession", reflect.TypeOf((*MockPARStorage)(nil).DeletePARSession), ctx, requestURI)
}

// GetPARSession mocks base method.
func (m *MockPARStorage) GetPARSession(ctx context.Context, requestURI string) (oauth2.AuthorizeRequester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPARSession", ctx, requestURI)
	ret0, _ := ret[0].(oauth2.AuthorizeRequester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPARSession indicates an expected call of GetPARSession.
func (mr *MockPARStorageMockRecorder) GetPARSession(ctx, requestURI any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPARSession", reflect.TypeOf((*MockPARStorage)(nil).GetPARSession), ctx, requestURI)
}
