// Code generated by MockGen. DO NOT EDIT.
// Source: authelia.com/provider/oauth2/handler/rfc7591 (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package mock -destination testing/mock/rfc7591_storage.go -mock_names Storage=MockRFC7591Storage authelia.com/provider/oauth2/handler/rfc7591 Storage
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"
	time "time"

	oauth2 "authelia.com/provider/oauth2"
	gomock "go.uber.org/mock/gomock"
)

// MockRFC7591Storage is a mock of Storage interface.
type MockRFC7591Storage struct {
	ctrl     *gomock.Controller
	recorder *MockRFC7591StorageMockRecorder
	isgomock struct{}
}

// MockRFC7591StorageMockRecorder is the mock recorder for MockRFC7591Storage.
type MockRFC7591StorageMockRecorder struct {
	mock *MockRFC7591Storage
}

// NewMockRFC7591Storage creates a new mock instance.
func NewMockRFC7591Storage(ctrl *gomock.Controller) *MockRFC7591Storage {
	mock := &MockRFC7591Storage{ctrl: ctrl}
	mock.recorder = &MockRFC7591StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRFC7591Storage) EXPECT() *MockRFC7591StorageMockRecorder {
	return m.recorder
}

// ClientAssertionJWTValid mocks base method.
func (m *MockRFC7591Storage) ClientAssertionJWTValid(ctx context.Context, jti string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientAssertionJWTValid", ctx, jti)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClientAssertionJWTValid indicates an expected call of ClientAssertionJWTValid.
func (mr *MockRFC7591StorageMockRecorder) ClientAssertionJWTValid(ctx, jti any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientAssertionJWTValid", reflect.TypeOf((*MockRFC7591Storage)(nil).ClientAssertionJWTValid), ctx, jti)
}

// CreateAccessTokenSession mocks base method.
func (m *MockRFC7591Storage) CreateAccessTokenSession(ctx context.Context, signature string, request oauth2.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAccessTokenSession", ctx, signature, request)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAccessTokenSession indicates an expected call of CreateAccessTokenSession.
func (mr *MockRFC7591StorageMockRecorder) CreateAccessTokenSession(ctx, signature, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAccessTokenSession", reflect.TypeOf((*MockRFC7591Storage)(nil).CreateAccessTokenSession), ctx, signature, request)
}

// CreateClient mocks base method.
func (m *MockRFC7591Storage) CreateClient(ctx context.Context, client oauth2.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateClient", ctx, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateClient indicates an expected call of CreateClient.
func (mr *MockRFC7591StorageMockRecorder) CreateClient(ctx, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateClient", reflect.TypeOf((*MockRFC7591Storage)(nil).CreateClient), ctx, client)
}

// DeleteAccessTokenSession mocks base method.
func (m *MockRFC7591Storage) DeleteAccessTokenSession(ctx context.Context, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAccessTokenSession", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAccessTokenSession indicates an expected call of DeleteAccessTokenSession.
func (mr *MockRFC7591StorageMockRecorder) DeleteAccessTokenSession(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAccessTokenSession", reflect.TypeOf((*MockRFC7591Storage)(nil).DeleteAccessTokenSession), ctx, signature)
}

// DeleteClient mocks base method.
func (m *MockRFC7591Storage) DeleteClient(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteClient", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteClient indicates an expected call of DeleteClient.
func (mr *MockRFC7591StorageMockRecorder) DeleteClient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteClient", reflect.TypeOf((*MockRFC7591Storage)(nil).DeleteClient), ctx, id)
}

// GetAccessTokenSession mocks base method.
func (m *MockRFC7591Storage) GetAccessTokenSession(ctx context.Context, signature string, session oauth2.Session) (oauth2.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAccessTokenSession", ctx, signature, session)
	ret0, _ := ret[0].(oauth2.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAccessTokenSession indicates an expected call of GetAccessTokenSession.
func (mr *MockRFC7591StorageMockRecorder) GetAccessTokenSession(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAccessTokenSession", reflect.TypeOf((*MockRFC7591Storage)(nil).GetAccessTokenSession), ctx, signature, session)
}

// GetClient mocks base method.
func (m *MockRFC7591Storage) GetClient(ctx context.Context, id string) (oauth2.Client, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetClient", ctx, id)
	ret0, _ := ret[0].(oauth2.Client)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetClient indicates an expected call of GetClient.
func (mr *MockRFC7591StorageMockRecorder) GetClient(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetClient", reflect.TypeOf((*MockRFC7591Storage)(nil).GetClient), ctx, id)
}

// SetClientAssertionJWT mocks base method.
func (m *MockRFC7591Storage) SetClientAssertionJWT(ctx context.Context, jti string, exp time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetClientAssertionJWT", ctx, jti, exp)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetClientAssertionJWT indicates an expected call of SetClientAssertionJWT.
func (mr *MockRFC7591StorageMockRecorder) SetClientAssertionJWT(ctx, jti, exp any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetClientAssertionJWT", reflect.TypeOf((*MockRFC7591Storage)(nil).SetClientAssertionJWT), ctx, jti, exp)
}

// UpdateClient mocks base method.
func (m *MockRFC7591Storage) UpdateClient(ctx context.Context, id string, client oauth2.Client) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateClient", ctx, id, client)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateClient indicates an expected call of UpdateClient.
func (mr *MockRFC7591StorageMockRecorder) UpdateClient(ctx, id, client any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateClient", reflect.TypeOf((*MockRFC7591Storage)(nil).UpdateClient), ctx, id, client)
}
