name: 'Code Quality'
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
jobs:
  format-goimports-reviser:
    name: 'Format (goimports-reviser)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.26'
      - name: 'Run Go Imports Reviser'
        run: |
          make format-goimports-reviser
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  format-prettier:
    name: 'Format (prettier)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (pnpm)'
        uses: pnpm/action-setup@903f9c1a6ebcba6cf41d87230be49611ac97822e # v6.0.3
        with:
          version: 10
      - name: 'Run Prettier'
        run: |
          make format-prettier
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  generate:
    name: 'Generate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@8d3c67de8e2fe68ef647c8db1e6a09f647780f40 # v2.19.0
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@4a3601121dd01d1626a1e23e37211e3254c1c06c # v6.4.0
        with:
          go-version: '1.26'
      - name: 'Run Generate'
        run: |
          make generate
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
