name: 'Code Quality'
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
jobs:
  format-goimports-reviser:
    name: 'Format (goimports-reviser)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26'
      - name: 'Run Go Imports Reviser'
        run: |
          make format-goimports-reviser
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  format-prettier:
    name: 'Format (prettier)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (pnpm)'
        uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v4.4.0
        with:
          version: 10
      - name: 'Run Prettier'
        run: |
          make format-prettier
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  generate:
    name: 'Generate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@fa2e9d605c4eeb9fcad4c99c224cee0c6c7f3594 # v2.16.0
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: 'Setup (go)'
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 # v6.3.0
        with:
          go-version: '1.26'
      - name: 'Run Generate'
        run: |
          make generate
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
