# SPDX-FileCopyrightText: 2026 Authelia
#
# SPDX-License-Identifier: Apache-2.0

name: 'Code Quality'
on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
permissions:
  contents: 'read'
jobs:
  format-goimports-reviser:
    name: 'Format (goimports-reviser)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Setup (go)'
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26'
      - name: 'Run Go Imports Reviser'
        run: |
          make format-goimports-reviser
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  format-prettier:
    name: 'Format (prettier)'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Setup (pnpm)'
        uses: pnpm/action-setup@0977fd99725f1db4007ccb2928dbb4e90d06cc86 # v6.0.10
        with:
          version: 11
      - name: 'Run Prettier'
        run: |
          make format-prettier
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
  generate:
    name: 'Generate'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Harden Runner'
        uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
        with:
          egress-policy: 'audit'
      - name: 'Checkout'
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: 'Setup (go)'
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version: '1.26'
      - name: 'Run Generate'
        run: |
          make generate
      - name: 'Feedback'
        run: |
          git diff HEAD --exit-code --color
