name: Format

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v3
        with:
          go-version: 1.21
      - run: make format
      - name: Indicate formatting issues
        run: git diff HEAD --exit-code --color
